name: Run SonarCloud on Back-end

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

      
jobs:
  tests-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}