name: Run SonarCloud on Front-end

on:
  pull_request:
    branches:
      - 'main'

jobs:
  sonar-front:
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Scan with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
        with:
          args:
            -Dsonar.organization=codebygaetan
            -Dsonar.projectKey=codebygaetan_BobApp_front
            -Dsonar.projectName=BobApp_front
            -Dsonar.projectBaseDir=front/