name: Run tests on Front-end

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 20.9.0
      - name: Install Dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test:prod

      - name: Archive Karma coverage report
        uses: actions/upload-artifact@v4
        with:
          name: karma-report
          path: front/coverage/bobapp