name: Run tests on Back-end

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean verify

      - name: Log coverage percentages to workflow output
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Archive Jacoco reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: back/target/site/jacoco