name: Run tests on Back-end

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: echo "A faire"
        # run: actions/checkout@v3