name: Run tests on Front-end

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests-front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 20.9.0
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm test