name: Run tests on Back-end

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn clean install

      - name: Generate JaCoCo badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: back/target/site/jacoco/jacoco.csv
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true

      - name: Archive Jacoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco